default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      threads: 4
      keyfile: "{{ env_var('BQ_KEYFILE_PATH') }}"
